name: convml_data

channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - netcdf4
  - git
  - xarray
  - cartopy
  - xesmf
  # must install pykdtre with conda so that it matches numpy
  - pykdtree
