name: Python Package using Conda
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    defaults:
      run:
        shell: bash -l {0}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          extra-specs: |
            python=${{ matrix.python-version }}
      - run: mamba --version
      - run: which python
      - name: install convml_data
        run: |
          pip install .
          pip install ".[sattiles]"
# 2021/2/24: skip linting for now
#      - name: Lint with flake8
#        run: |
#          conda install flake8
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
